apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vkhj26/hipstershop-gitops.git
    targetRevision: HEAD
    path: apps/hipstershop

  destination:
    server: https://kubernetes.default.svc
    namespace: hipstershop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true