apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    # EL CAMBIO ESTÁ AQUÍ: Quitamos "/keycloak" de la URL
    repoURL: https://charts.bitnami.com/bitnami 
    chart: keycloak
    targetRevision: 21.0.2 # Usa esta versión que es más estable para pruebas
    helm:
      values: |
        image:
          registry: docker.io
          repository: bitnamilegacy/keycloak
          tag: latest
        auth:
          adminUser: admin
          adminPassword: admin1234
        postgresql:
          enabled: true
          auth:
            username: bn_keycloak
            password: admin1234 # Ponemos la misma que el admin para no liarnos
            database: bitnami_keycloak
          image:
            registry: docker.io
            repository: bitnamilegacy/postgresql
            tag: 15-debian-11
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true