image:
  repository: bitnami/keycloak
  tag: 26.3.1-debian-12-r1

auth:
  adminUser: admin
  adminPassword: admin12345

service:
  type: ClusterIP

postgresql:
  enabled: true

keycloakConfigCli:
  enabled: true
  image:
    repository: bitnami/keycloak-config-cli
  configuration:
    existingConfigmap: keycloak-config