image:
  repository: bitnami/keycloak
  tag: 17.5.0-debian-12-r0

auth:
  adminUser: admin
  adminPassword: admin12345

service:
  type: ClusterIP

postgresql:
  enabled: true

keycloakConfigCli:
  enabled: true
  image:
    repository: bitnami/keycloak-config-cli
  configuration:
    existingConfigmap: keycloak-config